# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ruslan Osipov
email: ""
description: Notes on technology, travel, productivity, finance, and everything in between.
baseurl: ""
url: "https://rosipov.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-sitemap

sass:
  quiet_deps: true  # Minima theme generates SASS warnings, silence them.

paginate: 5
paginate_path: "posts/:num/"

feed:
  path: /atom.xml  # Compatible with Octopress path.

disqus:
  shortname: rosipov

google_analytics: UA-48506044-1

# Exclude from processing, in addition to the default list.
exclude:
  - .github/
  - README.markdown

permalink: /blog/:title/

defaults:
  -
    # Don't have to specify `layout: post` in the front matter of every post.
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

category_path: categories
